name: cards_activity_app
description: A Flutter app for managing a hand of cards.
publish_to: 'none' # Remove this line if you intend to publish the package.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+4
  path_provider: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
